export function switch_latte() {
  const root = <HTMLElement>document.querySelector(":root");
  document.documentElement.dataset.theme = "latte";
  root.style.setProperty("--ctp-crust", "#dce0e8");
  root.style.setProperty("--ctp-mantle", "#e6e9ef");
  root.style.setProperty("--ctp-base", "#eff1f5");
  root.style.setProperty("--ctp-surface0", "#ccd0da");
  root.style.setProperty("--ctp-surface1", "#bcc0cc");
  root.style.setProperty("--ctp-surface2", "#acb0be");
  root.style.setProperty("--ctp-overlay0", "#9ca0b0");
  root.style.setProperty("--ctp-overlay1", "#8c8fa1");
  root.style.setProperty("--ctp-overlay2", "#7c7f93");
  root.style.setProperty("--ctp-subtext0", "#6c6f85");
  root.style.setProperty("--ctp-subtext1", "#5c5f77");
  root.style.setProperty("--ctp-text", "#4c4f69");
  root.style.setProperty("--ctp-lavender", "#7287fd");
  root.style.setProperty("--ctp-blue", "#1e66f5");
  root.style.setProperty("--ctp-sapphire", "#209fb5");
  root.style.setProperty("--ctp-sky", "#04a5e5");
  root.style.setProperty("--ctp-teal", "#179299");
  root.style.setProperty("--ctp-green", "#40a02b");
  root.style.setProperty("--ctp-yellow", "#df8e1d");
  root.style.setProperty("--ctp-peach", "#fe640b");
  root.style.setProperty("--ctp-maroon", "#e64553");
  root.style.setProperty("--ctp-red", "#d20f39");
  root.style.setProperty("--ctp-mauve", "#8839ef");
  root.style.setProperty("--ctp-pink", "#ea76cb");
  root.style.setProperty("--ctp-flamingo", "#dd7878");
  root.style.setProperty("--ctp-rosewater", "#dc8a78");
}

export function switch_mocha() {
  const root = <HTMLElement>document.querySelector(":root");
  document.documentElement.dataset.theme = "mocha";
  root.style.setProperty("--ctp-crust", "#11111b");
  root.style.setProperty("--ctp-mantle", "#181825");
  root.style.setProperty("--ctp-base", "#1e1e2e");
  root.style.setProperty("--ctp-surface0", "#313244");
  root.style.setProperty("--ctp-surface1", "#45475a");
  root.style.setProperty("--ctp-surface2", "#585b70");
  root.style.setProperty("--ctp-overlay0", "#6c7086");
  root.style.setProperty("--ctp-overlay1", "#7f849c");
  root.style.setProperty("--ctp-overlay2", "#9399b2");
  root.style.setProperty("--ctp-subtext0", "#a6adc8");
  root.style.setProperty("--ctp-subtext1", "#bac2de");
  root.style.setProperty("--ctp-text", "#cdd6f4");
  root.style.setProperty("--ctp-lavender", "#b4befe");
  root.style.setProperty("--ctp-blue", "#89b4fa");
  root.style.setProperty("--ctp-sapphire", "#74c7ec");
  root.style.setProperty("--ctp-sky", "#89dceb");
  root.style.setProperty("--ctp-teal", "#94e2d5");
  root.style.setProperty("--ctp-green", "#a6e3a1");
  root.style.setProperty("--ctp-yellow", "#f9e2af");
  root.style.setProperty("--ctp-peach", "#fab387");
  root.style.setProperty("--ctp-maroon", "#eba0ac");
  root.style.setProperty("--ctp-red", "#f38ba8");
  root.style.setProperty("--ctp-mauve", "#cba6f7");
  root.style.setProperty("--ctp-pink", "#f5c2e7");
  root.style.setProperty("--ctp-flamingo", "#f2cdcd");
  root.style.setProperty("--ctp-rosewater", "#f5e0dc");
}
